language: python

python:
    - "2.7"

addons:
    - postgresql: "9.4"

install:
    - pip install -r requirements.txt
    - pip install coveralls

before_script:
    - psql -c 'create database pagoeta_test;' -U postgres
    - python manage.py migrate

script:
    - coverage run --source='pagoeta/apps' manage.py test pagoeta.apps

after_success:
    - coveralls
