language: python

python:
    - "3.6"

install:
    - pip install --upgrade pip && pip install pipenv coveralls

script:
    - coverage run --source=pagoeta -m unittest discover

after_success:
    - coveralls
